<?php

/**
 * Implements hook_locale_translation_projects_alter().
 */
function premium_theme_helper_locale_translation_projects_alter(&$projects) {
  $module_handler = \Drupal::service('module_handler');
  $path = $module_handler->getModule('premium_theme_helper')->getPath();
  $projects['premium_theme_helper']['info']['interface translation server pattern'] = $path.'/translations/%language.po';
}

/**
 * Implements hook_theme().
 */
function premium_theme_helper_theme($existing, $type, $theme, $path) {
  return [
    'page_title' => [
      'variables' => [
        'title' => ''
      ]
    ],
  ];
}

require_once __DIR__ . '/includes/layout-builder.inc';
